export const ACTIONS_TYPES = {


	GET_POST_BEGIN: 'GET_POST_BEGIN',
	GET_POST_SUCCESS: 'GET_POST_SUCCESS',
	GET_POST_FAILURE: 'GET_POST_FAILURE',

	GET_POSTS_BEGIN: 'GET_POSTS_BEGIN',
	GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
	GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

	CLEAR_POST_DATA: 'CLEAR_POST_DATA'

};